# Generated by Django 3.2.16 on 2024-09-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id_published',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id_published',
        ),
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию', verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию', verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='\n        Идентификатор страницы для URL;\n        разрешены символы латиницы, цифры, дефис и подчёркивание.\n        ', verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(help_text='\n        Если установить дату и время\n        в будущем — можно делать отложенные публикации.\n        ', verbose_name='Дата и время публикации'),
        ),
    ]
